aws_region                 = "us-east-1"
vpc_name                   = "jenkins-vpc"
vpc_cidr                   = "10.0.0.0/16"
public_subnets             = ["10.0.1.0/24"]
security_group_name        = "jenkins-sg"
security_group_description = "This security group is for Jenkins server"
number_of_instances        = ["server-1", "server-2"]
ami                        = "ami-04b70fa74e45c3917"
instance_type              = "t2.micro"
key_name                   = "mykey"